spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}
logging:
  file:
    path: logs/
external:
  apartment-api:
    path: http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade
    service-key:
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/house
    driver-class-name: org.mariadb.jdbc.Driver
    username: house
    password: house
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  batch:
    jdbc:
      initialize-schema: always
decorator:
  datasource:
    p6spy:
      enable-logging: true
      log-file: logs/spy.sql
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2
